d = {}

name = input("Entar friends name : ")
lang = input("Entar language name  : ")
d.update({name : lang})
name = input("Entar friends name : ")
lang = input("Entar language name  : ")
d.update({name : lang})
name = input("Entar friends name : ")
lang = input("Entar language name  : ")
d.update({name : lang})
name = input("Entar friends name : ")
lang = input("Entar language name  : ")
d.update({name : lang})
print(d)